# Generated by Django 5.2.6 on 2025-09-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_courses_enrolled",
                    models.IntegerField(default=0, verbose_name="cours inscrits"),
                ),
                (
                    "total_courses_completed",
                    models.IntegerField(default=0, verbose_name="cours complétés"),
                ),
                (
                    "total_lessons_completed",
                    models.IntegerField(default=0, verbose_name="leçons complétées"),
                ),
                (
                    "total_study_time",
                    models.IntegerField(
                        default=0, verbose_name="temps total (secondes)"
                    ),
                ),
                (
                    "total_quizzes_passed",
                    models.IntegerField(default=0, verbose_name="quiz réussis"),
                ),
                (
                    "average_quiz_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="score moyen quiz",
                    ),
                ),
                (
                    "average_progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="progression moyenne",
                    ),
                ),
                (
                    "current_streak_days",
                    models.IntegerField(
                        default=0, verbose_name="série actuelle (jours)"
                    ),
                ),
                (
                    "longest_streak_days",
                    models.IntegerField(
                        default=0, verbose_name="plus longue série (jours)"
                    ),
                ),
                (
                    "last_study_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="dernière étude"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "statistiques utilisateur",
                "verbose_name_plural": "statistiques utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="complété"),
                ),
                (
                    "time_spent",
                    models.IntegerField(
                        default=0, verbose_name="temps passé (secondes)"
                    ),
                ),
                (
                    "video_position",
                    models.IntegerField(
                        default=0, verbose_name="position vidéo (secondes)"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="commencé le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="complété le"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="dernier accès"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to="enrollments.enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "progression de leçon",
                "verbose_name_plural": "progressions de leçons",
                "ordering": ["enrollment", "lesson__module__order", "lesson__order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="score"
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="nombre questions"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="réponses correctes"),
                ),
                (
                    "time_taken",
                    models.IntegerField(
                        default=0, verbose_name="temps pris (secondes)"
                    ),
                ),
                (
                    "is_passed",
                    models.BooleanField(default=False, verbose_name="réussi"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="terminé le"
                    ),
                ),
                (
                    "answers",
                    models.JSONField(blank=True, default=dict, verbose_name="réponses"),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="enrollments.enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        limit_choices_to={"lesson_type": "quiz"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "tentative de quiz",
                "verbose_name_plural": "tentatives de quiz",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="fin"),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, verbose_name="durée (secondes)"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "lessons_viewed",
                    models.ManyToManyField(
                        related_name="study_sessions", to="courses.lesson"
                    ),
                ),
            ],
            options={
                "verbose_name": "session d'étude",
                "verbose_name_plural": "sessions d'étude",
                "ordering": ["-started_at"],
            },
        ),
    ]
