# Generated by Django 5.2.6 on 2025-09-19 11:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "favori",
                "verbose_name_plural": "favoris",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="note",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="commentaire"
                    ),
                ),
                (
                    "content_quality",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="qualité contenu",
                    ),
                ),
                (
                    "instructor_quality",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="qualité instructeur",
                    ),
                ),
                (
                    "value_for_money",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rapport qualité/prix",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="vérifié"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="mis en avant"),
                ),
                (
                    "helpful_count",
                    models.IntegerField(default=0, verbose_name="votes utiles"),
                ),
            ],
            options={
                "verbose_name": "avis",
                "verbose_name_plural": "avis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="progression (%)",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="inscrit le"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="commencé le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="complété le"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="dernier accès"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="complété"),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="favori"),
                ),
                (
                    "total_time_spent",
                    models.IntegerField(
                        default=0, verbose_name="temps total (secondes)"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscription",
                "verbose_name_plural": "inscriptions",
                "ordering": ["-enrolled_at"],
            },
        ),
    ]
