# Generated by Django 5.2.6 on 2025-09-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "certificate_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="ID certificat",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="code vérification",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="délivré le"),
                ),
                (
                    "student_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nom étudiant"
                    ),
                ),
                (
                    "course_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="titre cours"
                    ),
                ),
                (
                    "instructor_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nom instructeur"
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date complétion"
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="score final",
                    ),
                ),
                ("is_valid", models.BooleanField(default=True, verbose_name="valide")),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="téléchargements"),
                ),
            ],
            options={
                "verbose_name": "certificat",
                "verbose_name_plural": "certificats",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("template_file", models.FileField(upload_to="certificate_templates/")),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificate_backgrounds/"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#4A90E2",
                        max_length=7,
                        verbose_name="couleur principale",
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Inter", max_length=100, verbose_name="police"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="par défaut"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "template de certificat",
                "verbose_name_plural": "templates de certificats",
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
