# Generated by Django 5.2.6 on 2025-09-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificates", "0002_initial"),
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate",
                to="enrollments.enrollment",
            ),
        ),
    ]
