# Generated by Django 5.2.6 on 2025-09-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="icône"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4A90E2", max_length=7, verbose_name="couleur"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "catégorie",
                "verbose_name_plural": "catégories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=250, verbose_name="slug"),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("video", "Vidéo"),
                            ("text", "Texte"),
                            ("quiz", "Quiz"),
                            ("exercise", "Exercice"),
                        ],
                        default="video",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="contenu")),
                ("video_url", models.URLField(blank=True, verbose_name="URL vidéo")),
                (
                    "duration",
                    models.IntegerField(default=0, verbose_name="durée (minutes)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ordre")),
                ("resources", models.TextField(blank=True, verbose_name="ressources")),
                (
                    "is_preview",
                    models.BooleanField(default=False, verbose_name="aperçu gratuit"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "leçon",
                "verbose_name_plural": "leçons",
                "ordering": ["module", "order"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ordre")),
                (
                    "duration",
                    models.IntegerField(default=0, verbose_name="durée (minutes)"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "module",
                "verbose_name_plural": "modules",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="description courte"),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="description complète"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course_images/",
                        verbose_name="image",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Débutant"),
                            ("intermediate", "Intermédiaire"),
                            ("advanced", "Avancé"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="difficulté",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=0, verbose_name="durée (minutes)"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="prix"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="note"
                    ),
                ),
                (
                    "total_students",
                    models.IntegerField(default=0, verbose_name="étudiants"),
                ),
                ("total_reviews", models.IntegerField(default=0, verbose_name="avis")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="publié"),
                ),
                ("is_new", models.BooleanField(default=True, verbose_name="nouveau")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="mis en avant"),
                ),
                (
                    "prerequisites",
                    models.TextField(blank=True, verbose_name="prérequis"),
                ),
                (
                    "learning_objectives",
                    models.TextField(blank=True, verbose_name="objectifs"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="courses.category",
                        verbose_name="catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "cours",
                "verbose_name_plural": "cours",
                "ordering": ["-created_at"],
            },
        ),
    ]
